#pragma once

#include "math/aabb.h"

#include "core/app.h"
#include "core/window.h"
#include "core/error.h"
#include "core/log.h"
#include "core/scene.h"
#include "core/scene_manager.h"
#include "core/virtual_file_system.h"
#include "core/directory_storage_provider.h"
#include "core/package_storage_provider.h"

#include "ecs/entity.h"
#include "ecs/registry.h"
#include "ecs/system.h"
#include "ecs/behavior.h"
#include "core/transform.h"
#include "graphics/mesh_renderer.h"
#include "graphics/sprite.h"
#include "graphics/camera.h"
#include "graphics/light.h"
#include "physics/lifetime.h"
#include "physics/rigidbody.h"
#include "physics/box_collider.h"
#include "physics/facing.h"
#include "audio/audio_source.h"
#include "ui/ui_transform.h"
#include "ui/ui_rect.h"
#include "ui/ui_text.h"
#include "ui/ui_collider.h"
#include "ui/ui_button.h"

#include "graphics/render_system.h"
#include "physics/lifetime_system.h"
#include "physics/physics_system.h"
#include "audio/audio_system.h"
#include "ui/ui_system.h"

#include "input/input_manager.h"

#include "graphics/vertex.h"
#include "graphics/shader.h"
#include "graphics/mesh.h"
#include "graphics/texture.h"
#include "graphics/material.h"
#include "graphics/renderer.h"
#include "graphics/debug_renderer.h"

#include "audio/sound.h"
#include "audio/audio_engine.h"

#include "ui/font.h"

#include "assets/assets.h"
#include "assets/resource_manager.h"
